version: "3.8"
services:
  db:
    image: postgres:15
    container_name: django_postgres
    environment:
      POSTGRES_DB: yummy_restaurant
      POSTGRES_USER: yummy
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - yummy_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yummy -d yummy_restaurant"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: . # Використовує Dockerfile у поточному каталозі
    container_name: django_web
    working_dir: /code
    command: >
      bash -c "
        echo 'Waiting for postgres...' &&
        while ! pg_isready -U yummy -d yummy_restaurant; do sleep 1; done &&
        echo 'PostgreSQL started' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yummy_default
    restart: always

networks:
  yummy_default:

volumes:
  postgres_data: